# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import facemash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=facemash.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=500)),
                ('width_field', models.IntegerField(default=850)),
                ('Discription', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rank_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_a', models.IntegerField()),
                ('id_b', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
