# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='picture',
        ),
    ]
