# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import facemash.models


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0002_auto_20160622_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='picture',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=facemash.models.upload_location, width_field='width_field'),
        ),
    ]
