# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0003_auto_20160622_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='nlikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
