# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0004_photo_nlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('t_l', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
