# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0005_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=1000),
        ),
    ]
