# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facemash', '0010_auto_20160630_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('n', 'n'), ('c', 'c')], max_length=100, null=True),
        ),
    ]
